geekshop_folder/geekshop/authapp/urls.py
from django.urls import path, re_path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

geekshop_folder/geekshop/basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

geekshop_folder/geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.views.generic.base import RedirectView
from mainapp import views as mainapp_views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include


urlpatterns = [
    path('', RedirectView.as_view(url="/index", permanent=False)),
    path('index/', mainapp_views.main, name = "index"),
    path('products/', include('mainapp.urls', namespace ='products'), name = 'products'),
    path('contact/', mainapp_views.contact, name = "contact"),
    path('basket/', include('basketapp.urls', namespace='basket')),
    # админка из коробки (defaultadmin) и пользовательская (adminapp)
    #path('defaultadmin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('', include('social_django.urls', namespace='social')),
    re_path(r'^order/', include('ordersapp.urls', namespace='order'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop_folder/geekshop/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
   path('', mainapp.products, name='index'),
   path('category/<int:pk>/', mainapp.products, name='category'),
   path('category/<int:pk>/page/<int:page>/', mainapp.products, name='page'),
   path('product/<int:pk>/', mainapp.product, name='product'),
]

geekshop_folder/geekshop/mainapp/models.py
from django.db import models

# Create your models here.
# условно класс=таблица в БД, переменные это столбцы таблицы, в атрибутах указываются свойства столбцов
class ProductCategory(models.Model):
    name = models.CharField(verbose_name='Название категории', max_length=64, unique=True)
    description = models.TextField(verbose_name='Краткое описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='активен', default=True)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

geekshop_folder/geekshop/mainapp/templates/mainapp/models.py
from django.db import models

# условно класс=таблица в БД, переменные это столбцы таблицы, в атрибутах указываются свойства столбцов
class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', unique=True)
    description = models.TextField(verbose_name='описание', blank=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

print(Product)

geekshop_folder/geekshop/mainapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import ProductCategory, Product
from random import sample
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

#ссылки для главного меню сайта
menu_links = [
    {"href": "index", "active_if": ["index"], "name": "Главная"},
    {
        "href": "products:index",
        "active_if": ["products:index", "products:category"],
        "name": "Продукты",
    },
    {"href": "contact", "active_if": ["contact"], "name": "Контакты"},
]

#вывод "горящего предложения" (с) перевод алиэкспресса
def get_hot_product():
    products = Product.objects.all()

    return sample(list(products), 1)[0]

#вывод похожих продуктов для горячего предложения
def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category). \
                        exclude(pk=hot_product.pk)[:3]

    return same_products


#контроллер главной страницы
def main(request):
    title = 'Главная'

    products = Product.objects.all()[:4]

    return render(request, 'mainapp/index.html', context={
        'menu_links': menu_links,
        "product_count": "9000",
        "shop_slogan": "лучшее для вас!",
        'title': title,
        'products': products})


#контроллер каталога продуктов
def products(request, pk=None, page=1):
    title = 'Продукты'
    products_menu = ProductCategory.objects.all()
    related_products = Product.objects.all()[:2] if not pk else Product.objects.filter(category__id=pk)
    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    if pk is not None:
        if pk == 0:
            products = Product.objects.all().order_by('price')
            category = {'name': 'Все', 'pk':0}
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')

        paginator = Paginator(products, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        return render(request, 'mainapp/products_list.html', context={'title': title,
                                                                      'menu_links': menu_links,
                                                                      'products_menu': products_menu,
                                                                      'category': category,
                                                                      'products': products_paginator,
                                                                      'related_products': related_products,
                                                                      'same_products': same_products})

    else:
        same_products = Product.objects.all()[:3]

        return render(request, 'mainapp/products.html', context={'title': title,
                                                                 'menu_links': menu_links,
                                                                 'products_menu': products_menu,
                                                                 'same_products': same_products,
                                                                 'hot_product': hot_product})


#контроллер страницы конкретного товара
def product(request, pk):
    title = 'Товар'

    content = {
        'title': title,
        'products_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
        "menu_links": menu_links,
    }

    return render(request, 'mainapp/product.html', content)


#контроллер страницы контактов
def contact(request):

    return render(request, 'mainapp/contact.html', context={"menu_links": menu_links})

geekshop_folder/geekshop/mainapp/templates/mainapp/base.html
{%load static%}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    {% block 'title' %}
    {% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% block js %}
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.0.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endblock %}
</head>
<body>
	<div class="container">
        {% block 'menu_class' %}
        {% endblock %}
        {% include 'mainapp/includes/inc_menu.html' %}
        {% block 'divs' %}
        {% endblock %}
    {% block 'content' %}
    {% endblock %}
    </div>

    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>

</body>
</html>

geekshop_folder/geekshop/mainapp/templates/mainapp/contact.html
{% extends "mainapp/base.html" %}
{%load static%}

	{% block 'title' %}
    <title>Контакты</title>
	{% endblock %}
		{%block 'menu_class' %}
			<div class="hero">
				<div class="header clearfix">
		{% endblock %}
		{% block 'divs' %}
				</div>
				<h1>Наши контакты</h1>
			</div>
		{% endblock %}

{% block 'content' %}
		<div class="location">
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
		</div>

		<div class="clr"></div>
	</div>	

geekshop_folder/geekshop/mainapp/templates/mainapp/index.html
{% extends "mainapp/base.html" %}
{%load static%}

{% block 'title' %}
<title>Магазин</title>
{% endblock %}
{% block 'menu_class' %}
<div class="slider">
    <div class="header clearfix">
        {% endblock %}
        {% block 'divs' %}
    </div>
    {% endblock %}
    {% block 'content' %}
    <div class="text-slider">
        <h3 class="green">тенденции</h3>
        <h3 class="big"> удобные стулья</h3>
        <p>Новый уровень комфорта. Отличные характеристики.</p>
        <p>Более {{product_count}} моделей на {% now "Y"%} год. {{shop_slogan | title}}</p>
        <a href="#" class="button-order">заказать <img src="/static/img/arrow.png" alt=""></a>
    </div>
    <div class="navi">
        <a href="#"></a><a href="#"></a><a href="#"></a>
    </div>
</div>

<div class="featured">
    <div class="featured-menu">
        <a class="active" href="#">Популярные</a><a href="#">Новинки</a>
    </div>
    <a class="explore" href="#">показать все <img src="/static/img/arrow.png" alt=""></a>
    <div class="clearfix">
    </div>
    <div class="tab-content">
        {% for product in products %}
        <div class="block">
            <a href="{% url 'products:product' product.pk %}">
                <img src="/media/{{ product.image }}" width="270" height="270"
                     alt="{{ product.short_desc }}">
                <div class="text">
                    <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                    <h3>{{ product.category.name }}</h3>
                    <h4>{{ product.name }}</h4>
                    <p>{{ product.description }}</p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
<div class="clr"></div>

    {% endblock %}

geekshop_folder/geekshop/mainapp/templates/mainapp/product.html
{% extends "mainapp/base.html" %}
{%load static%}

{% block 'title' %}
<title>Каталог</title>
{% endblock %}

{% block 'menu_class' %}
<div class="hero-white">
    <div class="header clearfix">
        {% endblock %}
        {% block 'divs' %}
    </div>
</div>
{% endblock %}
{% block 'content' %}
<div class="details">
    <div class="links clearfix">
        {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>

    <div class="details-products">
        <div class="details-slider">
            <div class="slider-product">
                <img src="/media/{{ product.image }}" width=350px height=350px
                     alt="{{ product.short_desc }}">
            </div>

            <div class="description">
                <h3 class="big-bold">{{ product.name }}</h3>
                <br>
                <p class="price"> {{ product.price }} <span>руб</span></p>
                <a href="{% url 'basket:add' product.pk %}" class="red-button">
                    заказать
                    <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    {{ product.description }}
                </div>
            </div>
        </div>
    </div>
</div>
<div class="clr"></div>
{% endblock %}

geekshop_folder/geekshop/mainapp/templates/mainapp/products.html
{% extends "mainapp/base.html" %}
{%load static%}

	{% block 'title' %}
	<title>Каталог</title>
	{% endblock %}

		{% block 'menu_class' %}
		<div class="hero-white">
			<div class="header clearfix">
		{% endblock %}
		{% block 'divs' %}
			</div>
		</div>
		{% endblock %}
		{% block 'content' %}
		<div class="details">
			<div class="links clearfix">
				{% include 'mainapp/includes/inc_categories_menu.html' %}
			</div>

			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">
					  <img src="/media/{{ hot_product.image }}" width="500" height="500">
					</div>
				</div>

				<div class="description">
					<div class="description">
					<h3 class="big-bold">{{ hot_product.name }}</h3>
					<h3 class="red">горячее предложение</h3>
					<p class="price">{{ hot_product.price }} <span>руб</span></p>
					<a href="{% url 'products:product' hot_product.pk %}" class="red-button">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">
					  {{ hot_product.description }}
					</div>
			</div>

			<div class="related">
				<div class="title clearfix">
					<h2>Похожие продукты</h2>
					<a class="explore" href="#">показать все <img src="/static/img/arrow.png" alt=""></a>
				</div>
				<div class="related-products clearfix">
					{% for product in same_products %}
					<div class="block">
						<a href="{% url 'products:product' product.pk %}">
      						<img src="/media/{{ product.image }}" width="370" height="370"
								 alt="{{ product.short_desc }}">
      						<div class="text">
        						<h3>{{ product.category.name }}</h3>
        						<h4>{{ product.name }}</h4>
        						<p>{{ product.description }}</p>
      						</div>
    					</a>
					</div>
					{% endfor %}
				</div>
			</div>
		</div>

		<div class="clr"></div>

geekshop_folder/geekshop/mainapp/templates/mainapp/products_list.html
{% extends "mainapp/base.html" %}
{%load static%}

{% block 'title' %}
<title>Товар</title>
{% endblock %}

{% block 'menu_class' %}
<div class="hero-white">
    <div class="header clearfix">
        {% endblock %}
        {% block 'divs' %}
    </div>
</div>
{% endblock %}
{% block 'content' %}
<div class="details">
    <div class="links clearfix">
        {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>

    <div class="products_list">
        <div class="title clearfix">
            <h2>Категория: {{ category.name|title }}</h2>
        </div>
        <div class="paginator">
          {% if products.has_previous %}
            <a href="{% url 'products:page' category.pk products.previous_page_number %}">
              назад <
            </a>
          {% endif %}
          <span class="current">
            страница {{ products.number }} из
            {{ products.paginator.num_pages }}
          </span>
          {% if products.has_next %}
            <a href="{% url 'products:page' category.pk products.next_page_number %}">
              > вперёд
            </a>
          {% endif %}
        </div>


        <div class="related-products clearfix">
            {% for product in products %}
            <div class="block">
                <a href="{% url 'products:product' product.pk %}">
                    <img src="/media/{{ product.image }}" width="370" height="370"
                         alt="{{ product.short_desc }}">
                    <div class="text">
                        <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                        <h3>{{ product.category.name }}</h3>
                        <h4>{{ product.name }}</h4>
                        <p>{{ product.description }}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>

    </div>
</div>

<div class="clr"></div>
{% endblock %}