geekshop_folder/geekshop/adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.ProductCategoriesListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.ProductsListView.as_view(), name='products'),
    path('products/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),
]

geekshop_folder/geekshop/authapp/urls.py
from django.urls import path, re_path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

geekshop_folder/geekshop/basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

geekshop_folder/geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.views.generic.base import RedirectView
from mainapp import views as mainapp_views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include


urlpatterns = [
    path('', RedirectView.as_view(url="/index", permanent=False)),
    path('index/', mainapp_views.main, name = "index"),
    path('products/', include('mainapp.urls', namespace ='products'), name = 'products'),
    path('contact/', mainapp_views.contact, name = "contact"),
    path('basket/', include('basketapp.urls', namespace='basket')),
    # админка из коробки (defaultadmin) и пользовательская (adminapp)
    #path('defaultadmin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('', include('social_django.urls', namespace='social')),
    re_path(r'^order/', include('ordersapp.urls', namespace='order'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop_folder/geekshop/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
   path('', mainapp.products, name='index'),
   path('category/<int:pk>/', mainapp.products, name='category'),
   path('category/<int:pk>/page/<int:page>/', mainapp.products, name='page'),
   path('product/<int:pk>/', mainapp.product, name='product'),
]

geekshop_folder/geekshop/ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import re_path

app_name="ordersapp"

urlpatterns = [
   re_path(r'^$', ordersapp.OrderList.as_view(), name='orders_list'),
   re_path(r'^forming/complete/(?P<pk>\d+)/$',
           ordersapp.order_forming_complete, name='order_forming_complete'),
   re_path(r'^create/$', ordersapp.OrderItemsCreate.as_view(),
           name='order_create'),
   re_path(r'^read/(?P<pk>\d+)/$', ordersapp.OrderRead.as_view(),
           name='order_read'),
   re_path(r'^update/(?P<pk>\d+)/$', ordersapp.OrderItemsUpdate.as_view(),
           name='order_update'),
   re_path(r'^delete/(?P<pk>\d+)/$', ordersapp.OrderDelete.as_view(),
           name='order_delete'),
]

geekshop_folder/geekshop/mainapp/models.py
from django.db import models

# Create your models here.
# условно класс=таблица в БД, переменные это столбцы таблицы, в атрибутах указываются свойства столбцов
class ProductCategory(models.Model):
    name = models.CharField(verbose_name='Название категории', max_length=64, unique=True)
    description = models.TextField(verbose_name='Краткое описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='активен', default=True)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

geekshop_folder/geekshop/mainapp/templates/mainapp/models.py
from django.db import models

# условно класс=таблица в БД, переменные это столбцы таблицы, в атрибутах указываются свойства столбцов
class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', unique=True)
    description = models.TextField(verbose_name='описание', blank=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

print(Product)

geekshop_folder/geekshop/mainapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import ProductCategory, Product
from random import sample
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

#ссылки для главного меню сайта
menu_links = [
    {"href": "index", "active_if": ["index"], "name": "Главная"},
    {
        "href": "products:index",
        "active_if": ["products:index", "products:category"],
        "name": "Продукты",
    },
    {"href": "contact", "active_if": ["contact"], "name": "Контакты"},
]

#вывод "горящего предложения" (с) перевод алиэкспресса
def get_hot_product():
    products = Product.objects.all()

    return sample(list(products), 1)[0]

#вывод похожих продуктов для горячего предложения
def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category). \
                        exclude(pk=hot_product.pk)[:3]

    return same_products


#контроллер главной страницы
def main(request):
    title = 'Главная'

    products = Product.objects.all()[:4]

    return render(request, 'mainapp/index.html', context={
        'menu_links': menu_links,
        "product_count": "9000",
        "shop_slogan": "лучшее для вас!",
        'title': title,
        'products': products})


#контроллер каталога продуктов
def products(request, pk=None, page=1):
    title = 'Продукты'
    products_menu = ProductCategory.objects.all()
    related_products = Product.objects.all()[:2] if not pk else Product.objects.filter(category__id=pk)
    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    if pk is not None:
        if pk == 0:
            products = Product.objects.all().order_by('price')
            category = {'name': 'Все', 'pk':0}
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')

        paginator = Paginator(products, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        return render(request, 'mainapp/products_list.html', context={'title': title,
                                                                      'menu_links': menu_links,
                                                                      'products_menu': products_menu,
                                                                      'category': category,
                                                                      'products': products_paginator,
                                                                      'related_products': related_products,
                                                                      'same_products': same_products})

    else:
        same_products = Product.objects.all()[:3]

        return render(request, 'mainapp/products.html', context={'title': title,
                                                                 'menu_links': menu_links,
                                                                 'products_menu': products_menu,
                                                                 'same_products': same_products,
                                                                 'hot_product': hot_product})


#контроллер страницы конкретного товара
def product(request, pk):
    title = 'Товар'

    content = {
        'title': title,
        'products_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
        "menu_links": menu_links,
    }

    return render(request, 'mainapp/product.html', content)


#контроллер страницы контактов
def contact(request):

    return render(request, 'mainapp/contact.html', context={"menu_links": menu_links})

geekshop_folder/geekshop/mainapp/templates/mainapp/includes/inc_categories_menu.html
<ul class="links-menu">
  <li>
    <a href="{% url 'products:category' 0 %}"
       class="{% if request.resolver_match.kwargs.pk == '0' %}
                active
              {% endif %}">
      все
    </a>
  </li>
  {% for link in products_menu %}
    <li>
      <a href="{% url 'products:category' link.id %}"
         class="{% if request.resolver_match.kwargs.pk|add:'0' == link.pk %}
                  active
                {% endif %}">
        {{ link.name }}
      </a>
    </li>
  {% endfor %}
</ul>

geekshop_folder/geekshop/mainapp/templates/mainapp/includes/inc_menu.html
<a href="index.html" class="logo"></a>
<ul class="menu">
    {% for link in menu_links %}
    <li><a href="{% url link.href %}"
           {% if request.resolver_match.view_name in link.active_if %}
           class="active"
           {% endif %}">
        {{ link.name }}
        </a>
    </li>
    {% endfor %}
    {% if user.is_authenticated %}
    <li>
       <div class="dropdown">
           <a class="dropdown-toggle" href="" data-toggle="dropdown">
               {{ user.first_name|default:'Пользователь' }}
               <span class="caret"></span>
           </a>
           <ul class="dropdown-menu">
               <li>
                   <a href="{% url 'auth:edit' %}">
                       профиль
                   </a>
               </li>
               <li>
                   <a href="{% url 'ordersapp:orders_list' %}">
                       заказы
                   </a>
               </li>
               {% if user.is_superuser %}
               <li>
                   <a href="{% url 'admin:users' %}">Админка</a>
               </li>
               {% endif %}
           </ul>
       </div>
   </li>
    {% endif %}
    <li>
        <a href="{% url 'basket:view' %}">
            Корзина
            {% if basket %}
            ({{ basket.0.total_quantity }}):
            {{ basket.0.total_cost|floatformat:0 }} руб
            {% endif %}
            </a>
    </li>
    <li>
        {% if user.is_authenticated %}
        <a href="{% url 'auth:logout' %}">Выйти</a>
        {% else %}
        <a href="{% url 'auth:login' %}">Войти</a>
        <a href="{% url 'auth:register' %}">Регистрация</a>
        {% endif %}
    </li>

</ul>
    <a href="#" class="search"></a>
<!--    {% comment %}-->
<!--    <a href="{% url 'basket:view' %}" class="basket">-->
<!--        <span>-->
<!--            {% if basket %}-->
<!--      {{ basket.0.total_cost|floatformat:0 }} руб-->
<!--      ({{ basket.0.total_quantity }} шт)-->
<!--        </span>-->
<!--    </a>-->
<!--    {% endcomment %}-->

geekshop_folder/geekshop/mainapp/templates/mainapp/includes/products_menu.html
{% load static %}

<div class="links clearfix">
    <ul class="links-menu">
        {% for link in product_menu_links %}
        <li><a href="{% url 'products:category' link.id %}"
             {% if request.resolver_match.url_name == link.href %} class="active"{% endif %}>
                {{link.name}}
                </a>
        </li>
        {% endfor %}
        <li><a href="{% url 'products:category' 0 %}"
               {% if request.resolver_match.kwargs.pk == '0' %} class="active" {% endif %}>
              Все товары
            </a>
        </li>
    </ul>
</div>